version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - ai_service
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
      - AI_SERVICE_URL=http://ai_service:8000/predict
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

  ai_service:
    build:
      context: ./ai_service
