services:
  postgres:
    image: postgres:16-alpine
    container_name: final_yr_proj_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: final_yr_proj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8.0-alpine
    container_name: final_yr_proj_valkey
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  postgres_data:
    driver: local
  valkey_data:
    driver: local
